/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    servers: Server;
    workflows: Workflow;
    credentials: Credential;
    executions: Execution;
    'data-tables': DataTable;
    'data-table-rows': DataTableRow;
    roles: Role;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    servers: ServersSelect<false> | ServersSelect<true>;
    workflows: WorkflowsSelect<false> | WorkflowsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    executions: ExecutionsSelect<false> | ExecutionsSelect<true>;
    'data-tables': DataTablesSelect<false> | DataTablesSelect<true>;
    'data-table-rows': DataTableRowsSelect<false> | DataTableRowsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'admin-settings': AdminSetting;
    jobs: Job;
    header: Header;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'admin-settings': AdminSettingsSelect<false> | AdminSettingsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'n8n-sync': TaskN8NSync;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Optional. When set, only users with this role or the Admin role can view this dashboard on the frontend.
   */
  requiredRole?: (string | null) | Role;
  layout: (
    | ServersStatusListBlock
    | WorkflowsListBlock
    | CredentialsHealthBlock
    | LatestExecutionsBlock
    | ExecutionErrorsBlock
    | DataTableViewerBlock
    | ChatEmbedBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServersStatusListBlock".
 */
export interface ServersStatusListBlock {
  title: string;
  description?: string | null;
  limit: number;
  statuses?: ('online' | 'degraded' | 'offline' | 'unknown')[] | null;
  showEnvironment?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'serversStatusList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowsListBlock".
 */
export interface WorkflowsListBlock {
  title: string;
  description?: string | null;
  server?: (string | null) | Server;
  limit: number;
  showServer?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workflowsList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servers".
 */
export interface Server {
  id: string;
  name: string;
  slug: string;
  environment: 'production' | 'staging' | 'development' | 'sandbox';
  status: 'online' | 'degraded' | 'offline' | 'unknown';
  /**
   * Base URL for the n8n instance, for example https://n8n.example.com.
   */
  baseURL: string;
  /**
   * API base path used by the sync job. Defaults to /api/v1 for self-hosted n8n.
   */
  apiPath: string;
  /**
   * Optional direct link to the n8n UI for this server.
   */
  dashboardURL?: string | null;
  /**
   * Stored for future n8n sync jobs. Hidden from public reads.
   */
  apiKey: string;
  /**
   * When enabled, the Payload sync job will import data from this n8n server.
   */
  syncEnabled?: boolean | null;
  healthSummary?: string | null;
  lastSyncedAt?: string | null;
  lastSuccessfulSyncAt?: string | null;
  lastSyncStatus: 'idle' | 'running' | 'success' | 'error';
  lastSyncError?: string | null;
  /**
   * Opaque checkpoint data for incremental syncs, such as pagination or updated-after cursors.
   */
  syncCursor?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CredentialsHealthBlock".
 */
export interface CredentialsHealthBlock {
  title: string;
  description?: string | null;
  server?: (string | null) | Server;
  limit: number;
  onlyUnhealthy?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'credentialsHealth';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestExecutionsBlock".
 */
export interface LatestExecutionsBlock {
  title: string;
  description?: string | null;
  server?: (string | null) | Server;
  workflow?: (string | null) | Workflow;
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestExecutions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: string;
  name: string;
  /**
   * Raw workflow ID returned by n8n. Not globally unique across multiple servers.
   */
  workflowID: string;
  /**
   * Stable sync key in the form "<server-slug>:<workflowID>". Used for idempotent upserts.
   */
  sourceKey: string;
  server: string | Server;
  status: 'active' | 'paused' | 'error' | 'archived';
  active?: boolean | null;
  tags?: string[] | null;
  projectID?: string | null;
  versionID?: string | null;
  triggerCount?: number | null;
  nodeCount?: number | null;
  /**
   * Link to open the workflow in n8n.
   */
  n8nURL?: string | null;
  lastExecutionAt?: string | null;
  remoteUpdatedAt?: string | null;
  remoteCreatedAt?: string | null;
  lastSeenAt?: string | null;
  notes?: string | null;
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Redacted raw workflow payload from the n8n API for debugging sync mismatches.
   */
  apiData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExecutionErrorsBlock".
 */
export interface ExecutionErrorsBlock {
  title: string;
  description?: string | null;
  server?: (string | null) | Server;
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'executionErrors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataTableViewerBlock".
 */
export interface DataTableViewerBlock {
  title: string;
  description?: string | null;
  table: string | DataTable;
  pagingMode: 'preview' | 'pagination';
  defaultSort:
    | 'createdUpdatedDesc'
    | 'updatedCreatedDesc'
    | 'remoteCreatedDesc'
    | 'remoteUpdatedDesc'
    | 'rowIndexAsc'
    | 'rowIndexDesc';
  pageSize: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dataTableViewer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-tables".
 */
export interface DataTable {
  id: string;
  name: string;
  slug: string;
  /**
   * Optional stable key for job-managed tables, for example "<server-slug>:daily-revenue".
   */
  sourceKey?: string | null;
  /**
   * n8n data table ID. Use sourceKey for globally unique upserts across multiple servers.
   */
  tableID?: string | null;
  server: string | Server;
  /**
   * n8n project or personal-space identifier when available.
   */
  projectID?: string | null;
  /**
   * n8n data tables are scoped to a project or a personal space.
   */
  scope: 'project' | 'personal';
  description?: string | null;
  /**
   * Optional API path or workflow identifier that produced this dataset.
   */
  sourcePath?: string | null;
  columns?:
    | {
        name: string;
        type: 'string' | 'number' | 'boolean' | 'date' | 'json';
        /**
         * n8n column ID from the Data Table API.
         */
        columnID?: string | null;
        index?: number | null;
        displayName?: string | null;
        /**
         * Legacy alias retained for viewer compatibility and migration support.
         */
        key?: string | null;
        /**
         * Legacy alias retained for viewer compatibility and migration support.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  rowCount?: number | null;
  lastRefreshedAt?: string | null;
  remoteCreatedAt?: string | null;
  remoteUpdatedAt?: string | null;
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChatEmbedBlock".
 */
export interface ChatEmbedBlock {
  title: string;
  description?: string | null;
  provider?: string | null;
  embedURL: string;
  height: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'chatEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  title?: string | null;
  description?: string | null;
  /**
   * Choose which form to render on the frontend.
   */
  form: string | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: string;
  name: string;
  /**
   * Raw credential ID returned by n8n. Not globally unique across multiple servers.
   */
  credentialID: string;
  /**
   * Stable sync key in the form "<server-slug>:<credentialID>". Used for idempotent upserts.
   */
  sourceKey: string;
  credentialType: string;
  server: string | Server;
  isHealthy?: boolean | null;
  isGlobal?: boolean | null;
  isManaged?: boolean | null;
  scopes?: string[] | null;
  lastUsedAt?: string | null;
  remoteCreatedAt?: string | null;
  remoteUpdatedAt?: string | null;
  lastSeenAt?: string | null;
  summary?: string | null;
  /**
   * Redacted credential payload returned by n8n when includeData=true.
   */
  dataPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executions".
 */
export interface Execution {
  id: string;
  /**
   * Raw execution ID returned by n8n. Not globally unique across multiple servers.
   */
  executionID: string;
  /**
   * Stable sync key in the form "<server-slug>:<executionID>". Used for idempotent upserts.
   */
  sourceKey: string;
  server: string | Server;
  workflow?: (string | null) | Workflow;
  status: 'success' | 'error' | 'running' | 'waiting' | 'canceled';
  mode?: string | null;
  retryOf?: string | null;
  waitTill?: string | null;
  startedAt: string;
  finishedAt?: string | null;
  durationMS?: number | null;
  lastSeenAt?: string | null;
  errorMessage?: string | null;
  /**
   * Visible to authenticated users only.
   */
  errorStack?: string | null;
  payloadPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Raw execution payload from the n8n API for audit/debug purposes.
   */
  apiData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-table-rows".
 */
export interface DataTableRow {
  id: string;
  table: string | DataTable;
  /**
   * Optional stable key for sync-managed rows, for example "<server-slug>:<table-id>:<row-id>".
   */
  sourceKey?: string | null;
  /**
   * Remote row identifier when available.
   */
  rowID?: string | null;
  rowIndex?: number | null;
  /**
   * Plain object keyed by the parent table column names.
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastSeenAt?: string | null;
  remoteCreatedAt?: string | null;
  remoteUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Assign one or more roles to this user.
   */
  roles?: (string | Role)[] | null;
  roleNames?: string[] | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'n8n-sync' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'n8n-sync' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'servers';
        value: string | Server;
      } | null)
    | ({
        relationTo: 'workflows';
        value: string | Workflow;
      } | null)
    | ({
        relationTo: 'credentials';
        value: string | Credential;
      } | null)
    | ({
        relationTo: 'executions';
        value: string | Execution;
      } | null)
    | ({
        relationTo: 'data-tables';
        value: string | DataTable;
      } | null)
    | ({
        relationTo: 'data-table-rows';
        value: string | DataTableRow;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  requiredRole?: T;
  layout?:
    | T
    | {
        serversStatusList?: T | ServersStatusListBlockSelect<T>;
        workflowsList?: T | WorkflowsListBlockSelect<T>;
        credentialsHealth?: T | CredentialsHealthBlockSelect<T>;
        latestExecutions?: T | LatestExecutionsBlockSelect<T>;
        executionErrors?: T | ExecutionErrorsBlockSelect<T>;
        dataTableViewer?: T | DataTableViewerBlockSelect<T>;
        chatEmbed?: T | ChatEmbedBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServersStatusListBlock_select".
 */
export interface ServersStatusListBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  limit?: T;
  statuses?: T;
  showEnvironment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowsListBlock_select".
 */
export interface WorkflowsListBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  server?: T;
  limit?: T;
  showServer?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CredentialsHealthBlock_select".
 */
export interface CredentialsHealthBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  server?: T;
  limit?: T;
  onlyUnhealthy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestExecutionsBlock_select".
 */
export interface LatestExecutionsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  server?: T;
  workflow?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExecutionErrorsBlock_select".
 */
export interface ExecutionErrorsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  server?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataTableViewerBlock_select".
 */
export interface DataTableViewerBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  table?: T;
  pagingMode?: T;
  defaultSort?: T;
  pageSize?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChatEmbedBlock_select".
 */
export interface ChatEmbedBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  provider?: T;
  embedURL?: T;
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servers_select".
 */
export interface ServersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  environment?: T;
  status?: T;
  baseURL?: T;
  apiPath?: T;
  dashboardURL?: T;
  apiKey?: T;
  syncEnabled?: T;
  healthSummary?: T;
  lastSyncedAt?: T;
  lastSuccessfulSyncAt?: T;
  lastSyncStatus?: T;
  lastSyncError?: T;
  syncCursor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows_select".
 */
export interface WorkflowsSelect<T extends boolean = true> {
  name?: T;
  workflowID?: T;
  sourceKey?: T;
  server?: T;
  status?: T;
  active?: T;
  tags?: T;
  projectID?: T;
  versionID?: T;
  triggerCount?: T;
  nodeCount?: T;
  n8nURL?: T;
  lastExecutionAt?: T;
  remoteUpdatedAt?: T;
  remoteCreatedAt?: T;
  lastSeenAt?: T;
  notes?: T;
  settings?: T;
  apiData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  name?: T;
  credentialID?: T;
  sourceKey?: T;
  credentialType?: T;
  server?: T;
  isHealthy?: T;
  isGlobal?: T;
  isManaged?: T;
  scopes?: T;
  lastUsedAt?: T;
  remoteCreatedAt?: T;
  remoteUpdatedAt?: T;
  lastSeenAt?: T;
  summary?: T;
  dataPreview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executions_select".
 */
export interface ExecutionsSelect<T extends boolean = true> {
  executionID?: T;
  sourceKey?: T;
  server?: T;
  workflow?: T;
  status?: T;
  mode?: T;
  retryOf?: T;
  waitTill?: T;
  startedAt?: T;
  finishedAt?: T;
  durationMS?: T;
  lastSeenAt?: T;
  errorMessage?: T;
  errorStack?: T;
  payloadPreview?: T;
  apiData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-tables_select".
 */
export interface DataTablesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sourceKey?: T;
  tableID?: T;
  server?: T;
  projectID?: T;
  scope?: T;
  description?: T;
  sourcePath?: T;
  columns?:
    | T
    | {
        name?: T;
        type?: T;
        columnID?: T;
        index?: T;
        displayName?: T;
        key?: T;
        label?: T;
        id?: T;
      };
  rowCount?: T;
  lastRefreshedAt?: T;
  remoteCreatedAt?: T;
  remoteUpdatedAt?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-table-rows_select".
 */
export interface DataTableRowsSelect<T extends boolean = true> {
  table?: T;
  sourceKey?: T;
  rowID?: T;
  rowIndex?: T;
  data?: T;
  lastSeenAt?: T;
  remoteCreatedAt?: T;
  remoteUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  roleNames?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Branding and content for the Payload admin panel (icon, login screen).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-settings".
 */
export interface AdminSetting {
  id: string;
  /**
   * Upload an SVG or image. If not set, the default Payload icon is used. This image is shown in the admin nav (top-left) and as the browser tab favicon.
   */
  adminIcon?: (string | null) | Media;
  /**
   * Logo shown on the login screen (e.g. full company logo). Separate from the small admin nav icon. If not set, the default Payload logo is used.
   */
  loginLogo?: (string | null) | Media;
  /**
   * Welcome message or instructions shown above the login form.
   */
  loginWelcomeContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Allow visitors to use the frontend create account page and sign-up links.
   */
  allowFrontendCreateAccount?: boolean | null;
  /**
   * Additional content shown below the welcome line, still inside the banner.
   */
  dashboardBannerExtraContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Background (light mode).
   */
  bannerBg?: string | null;
  /**
   * Text color (light mode).
   */
  bannerText?: string | null;
  /**
   * Link color (light mode).
   */
  bannerLink?: string | null;
  /**
   * Background (dark mode).
   */
  bannerBgDark?: string | null;
  /**
   * Text color (dark mode).
   */
  bannerTextDark?: string | null;
  /**
   * Link color (dark mode).
   */
  bannerLinkDark?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Logo displayed in the header. If not set, no logo will be shown.
   */
  logo?: (string | null) | Media;
  /**
   * Favicon (.ico file). If not set, the default favicon.ico will be used.
   */
  favicon?: (string | null) | Media;
  /**
   * Apple touch icon (typically 180x180 PNG). If not set, no apple touch icon will be used.
   */
  appleTouchIcon?: (string | null) | Media;
  /**
   * Custom scripts to include in the <head> section (e.g., analytics, tracking codes).
   */
  headerScripts?: string | null;
  /**
   * Meta tags to include in the <head> section (e.g., Google verification, Bing verification).
   */
  metaTags?: string | null;
  /**
   * Short title shown in the dashboard sidebar brand area.
   */
  dashboardSidebarLabel?: string | null;
  /**
   * Supporting text shown beneath the dashboard sidebar title.
   */
  dashboardSidebarText?: string | null;
  /**
   * Hide the desktop dashboard sidebar while keeping the page content visible.
   */
  hideDashboardSidebar?: boolean | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-settings_select".
 */
export interface AdminSettingsSelect<T extends boolean = true> {
  adminIcon?: T;
  loginLogo?: T;
  loginWelcomeContent?: T;
  allowFrontendCreateAccount?: T;
  dashboardBannerExtraContent?: T;
  bannerBg?: T;
  bannerText?: T;
  bannerLink?: T;
  bannerBgDark?: T;
  bannerTextDark?: T;
  bannerLinkDark?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  favicon?: T;
  appleTouchIcon?: T;
  headerScripts?: T;
  metaTags?: T;
  dashboardSidebarLabel?: T;
  dashboardSidebarText?: T;
  hideDashboardSidebar?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskN8n-sync".
 */
export interface TaskN8NSync {
  input: {
    /**
     * Optional Payload server document ID. Leave empty to sync every enabled server.
     */
    serverID?: string | null;
    resources?: ('workflows' | 'credentials' | 'executions' | 'dataTables')[] | null;
  };
  output: {
    resources?: ('workflows' | 'credentials' | 'executions' | 'dataTables')[] | null;
    syncedDocs?: number | null;
    syncedRows?: number | null;
    syncedTables?: number | null;
    serversProcessed?: number | null;
    results?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}